// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquaresApi.Data;

#nullable disable

namespace SquaresApi.Migrations
{
    [DbContext(typeof(PointsContext))]
    partial class PointsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("SquaresApi.Models.Point", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("INTEGER");

                    b.HasKey("PointId");

                    b.HasIndex("CoordinateX", "CoordinateY")
                        .IsUnique();

                    b.ToTable("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
